name: appecchio_mockup
description: Frontend-only Flutter mockup for APPecchio UX.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/appecchio_bg.png
